workflows:
  - .github/**/*.yml
documentation:
  - '**/*.md'
dependencies:
  - gradle/libs.versions.toml

bitrate:
  - bitrate/**
capacity:
  - capacity/**
length:
  - length/**
percentage:
  - percentage/**
temperature:
  - temperature/**
